{{- if and (eq .Values.loadbalancer.type "aws") .Values.loadbalancer.mqtt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: TBMQClusterELB=TBMQMqtt
    {{- if and (not .Values.loadbalancer.mqtt.mutualTls.enabled) .Values.loadbalancer.mqtt.tlsTermination.enabled }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.loadbalancer.mqtt.tlsTermination.certificateRef }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "mqtts,mqtt-wss"
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: {{ include "tbmq.node.label" . }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-ws
      port: 8084
      targetPort: 8084
    {{- if and (not .Values.loadbalancer.mqtt.mutualTls.enabled) .Values.loadbalancer.mqtt.tlsTermination.enabled }}
    # This way NLB acts as an TLS termination point and forwards decrypted traffic to 1883 port of the TBMQ.
    - name: mqtts
      port: 8883
      targetPort: 1883
    # This way NLB acts as an TLS termination point and forwards decrypted traffic to 8084 port of the TBMQ.
    - name: mqtt-wss
      port: 8085
      targetPort: 8084
    {{- else }}
    # This way NLB acts as a transparent load balancer and forwards all traffic to port 8883 without decryption.
    - name: mqtts
      port: 8883
      targetPort: 8883
    # This way NLB acts as a transparent load balancer and forwards all traffic to port 8085 without decryption.
    - name: mqtt-wss
      targetPort: 8085
      port: 8085
    {{- end }}
{{- end }}
