apiVersion: v2
appVersion: 2.2.0-SNAPSHOT
description: Helm chart for TBMQ cluster.
name: tbmq-cluster
type: application
version: 1.1.0
annotations:
  artifacthub.io/category: streaming-messaging
  licenses: Apache-2.0
  artifacthub.io/maintainers: |
    - name: dshvaika
      email: dshvaika@thingsboard.io
    - name: dlandiak
      email: dlandiak@thingsboard.io
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Release 1.1.0
      links:
        - name: GitHub PR
          url: https://github.com/thingsboard/helm-charts/pull/to_replace_with_pr_number
home: https://thingsboard.io/products/mqtt-broker/
icon: https://img.thingsboard.io/thingsboard_blue.svg
keywords:
  - tbmq
  - mqtt
  - broker
  - thingsboard
  - iot
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: redis-cluster
    version: 10.3.0
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: postgresql
    version: 15.5.38
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: kafka
    version: 29.3.4
    repository: oci://registry-1.docker.io/bitnamicharts
