{{- if and (eq .Values.loadbalancer.type "gcp") .Values.loadbalancer.http.enabled }}
{{- if .Values.loadbalancer.http.ssl.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.loadbalancer.http.ssl.certificateRef }}
spec:
  domains:
    {{-  range $domain := .Values.loadbalancer.http.ssl.domains }}
    - {{ $domain }}
    {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: tbmq-http-fe-config
spec:
  redirectToHttps:
    enabled: true
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.loadbalancer.http.ssl.enabled }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.loadbalancer.http.ssl.staticIP }}
    networking.gke.io/managed-certificates: {{ .Values.loadbalancer.http.ssl.certificateRef }}
    networking.gke.io/v1beta1.FrontendConfig: tbmq-http-fe-config
    {{- end }}
spec:
  ingressClassName: "gce"
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tbmq.node.label" . }}
                port:
                  name: http
{{- end }}
