{{- if and (eq .Values.loadbalancer.type "gcp") .Values.loadbalancer.http.enabled }}
{{- if .Values.loadbalancer.http.ssl.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.loadbalancer.http.ssl.certificateRef }}
spec:
  domains:
    {{- range $domain := .Values.loadbalancer.http.ssl.domains }}
    - {{ $domain | quote }}
    {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: tbmq-http-fe-config
spec:
  redirectToHttps:
    enabled: true
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- $defaults := dict -}}
    {{- if .Values.loadbalancer.http.ssl.enabled -}}
      {{- $_ := set $defaults "kubernetes.io/ingress.global-static-ip-name" (printf "%v" .Values.loadbalancer.http.ssl.staticIP) -}}
      {{- $_ = set $defaults "networking.gke.io/managed-certificates" (printf "%v" .Values.loadbalancer.http.ssl.certificateRef) -}}
      {{- $_ =  set $defaults "networking.gke.io/v1beta1.FrontendConfig" "tbmq-http-fe-config" -}}
    {{- end -}}
    {{- /* merge user annotations over defaults (user wins) */ -}}
    {{- $user := default dict .Values.loadbalancer.http.annotations -}}
    {{- $merged := mergeOverwrite $defaults $user -}}
    {{- toYaml $merged | nindent 4 }}
spec:
  ingressClassName: "gce"
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tbmq.node.label" . }}
                port:
                  name: http
{{- end }}
