{{- if and (eq .Values.loadbalancer.type "azure") .Values.loadbalancer.http.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- $defaults := dict
        "appgw.ingress.kubernetes.io/use-regex" "true"
        "appgw.ingress.kubernetes.io/request-timeout" "300"
      -}}
    {{- if .Values.loadbalancer.http.ssl.enabled -}}
      {{- $_ := set $defaults "appgw.ingress.kubernetes.io/appgw-ssl-certificate" (printf "%v" .Values.loadbalancer.http.ssl.certificateRef) -}}
      {{- $_ =  set $defaults "appgw.ingress.kubernetes.io/ssl-redirect" "true" -}}
    {{- end -}}
    {{- /* merge user annotations over defaults (user wins) */ -}}
    {{- $user := default dict .Values.loadbalancer.http.annotations -}}
    {{- $merged := mergeOverwrite $defaults $user -}}
    {{- toYaml $merged | nindent 4 }}
spec:
  ingressClassName: azure/application-gateway
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tbmq.node.label" . }}
                port:
                  name: http
{{- end }}
