{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) }}
{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-postgres-external
  namespace: {{ $namespace }}
type: Opaque
data:
  external-postgres-password: {{ .Values.externalPostgresql.password | b64enc }}
{{- end }}
