{{- $redis := index .Values "redis-cluster" -}}
{{- $external := index .Values "external-redis-cluster" -}}
{{- if and (not $redis.enabled) $external.usePassword  (empty $external.existingSecret) -}}
{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-redis-cluster-external
  namespace: {{ $namespace }}
type: Opaque
data:
  redis-password: {{ $external.password | b64enc }}
{{- end }}
