{{- if and .Values.license.secret (empty .Values.license.existingSecret) -}}
{{- $namespace := .Release.Namespace -}}
{{- $releaseName := .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tbmq-license-secret" $releaseName }}
  namespace: {{ $namespace }}
type: Opaque
data:
  license-key: {{ .Values.license.secret | b64enc }}
{{- end }}
