{{- if and (eq .Values.loadbalancer.type "nginx") .Values.loadbalancer.http.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-http-lb
  namespace: {{ .Release.Namespace }}
  {{- with .Values.loadbalancer.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tbmq.node.label" . }}
                port:
                  name: http
{{- end }}
