{{- if and (eq .Values.loadbalancer.type "nginx") .Values.loadbalancer.mqtt.enabled -}}
{{- $serviceType := .Values.loadbalancer.mqtt.type | default "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mqtt-lb
  namespace: {{ .Release.Namespace }}
  {{- with .Values.loadbalancer.mqtt.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $serviceType }}
  {{- if and (eq $serviceType "NodePort") (eq $serviceType "LoadBalancer") }}
  externalTrafficPolicy: Local
  {{- end }}
  selector:
    app: {{ include "tbmq.node.label" . }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-ws
      port: 8084
      targetPort: 8084
    - name: mqtts
      port: 8883
      targetPort: 8883
    - name: mqtt-wss
      port: 8085
      targetPort: 8085
{{- end }}
